language: node_js
node_js:
- '0.12'
- stable
sudo: false
install:
- npm install -g bower
- npm install
- bower install
script:
- npm run travis
after_script:
- cat ./tests/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
